"""rename authors for data migration

Revision ID: 2d2fd5b6584
Revises: d2f81c81ac
Create Date: 2015-02-24 12:01:56.141259

"""

# revision identifiers, used by Alembic.
revision = '2d2fd5b6584'
down_revision = 'd2f81c81ac'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'authors', new_column_name='_authors')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', '_authors', new_column_name='authors')
    ### end Alembic commands ###
