"""Add author table

Revision ID: 383397eef6b
Revises: 4808089c2c7
Create Date: 2015-02-24 11:43:27.803408

"""

# revision identifiers, used by Alembic.
revision = '383397eef6b'
down_revision = '4808089c2c7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('author')
    ### end Alembic commands ###
