"""Add authors column

Revision ID: 4808089c2c7
Revises: 29fa612b7c8
Create Date: 2015-02-21 16:39:30.743584

"""

# revision identifiers, used by Alembic.
revision = '4808089c2c7'
down_revision = '29fa612b7c8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('authors', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'authors')
    ### end Alembic commands ###
